### PR TITLE
chore(contributors) Add @taylorotwell

### PR DESCRIPTION
**Pull request by vonglasow**
Address hoaproject/Central#97

### CODE REVIEW

**Comment by Hywan** [comment]
Thanks!

**Review by Hywan — APPROVED** [review]
We used to sort them by lastname alphabetic order, but it's fine.

**Comment by vonglasow** [comment]
ok let me order it

**Comment by vonglasow** [comment]
@Hywan done

**Review by Hywan — APPROVED** [review]

**Comment by Hywan** [comment]
Awesome, thanks!

**Comment by Hywan** [comment]
You can merge it now.

**Pull request merged**
